// FETCH DATA TYPES
export const FECTH_DATA_SUCCESS = 'FECTH_DATA_SUCCESS';
export const FECTH_DATA_ERROR = 'FECTH_DATA_ERROR';
export const FETCH_DATA_LOADING = 'FETCH_DATA_LOADING';
export const FETCH_DATA_FIND_CURRENCY = 'FETCH_DATA_FIND_CURRENCY';

// FAVORITES DATA TYPES
export const FAVORITES_ADD = 'FAVORITES_ADD';
export const FAVORITES_DELETE = 'FAVORITES_DELETE';